/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

MERGE INTO Province AS TARGET
USING (VALUES
	('Heredia'),
	('Cartago'),
	('Puntarenas'),
	('Guanacaste'),
	('Limón'),
	('Alajuela'),
	('San José')
)
AS Source ([Name])
ON TARGET.Name = Source.Name
WHEN NOT MATCHED BY TARGET THEN
INSERT (Name)
VALUES (Name);


MERGE INTO Canton AS TARGET 
USING (VALUES
	/*Cantones de San José*/
	('San José', 'San José'),
	('Escazú', 'San José'),
	('Desamparados', 'San José'),
	('Puriscal', 'San José'),
	('Tarrazú', 'San José'),
	('Aserrí', 'San José'),
	('Mora', 'San José'),
	('Goicoechea', 'San José'),
	('Santa Ana', 'San José'),
	('Alajuelita', 'San José'),
	('Coronado', 'San José'),
	('Acosta', 'San José'),
	('Tibás', 'San José'),
	('Moravia', 'San José'),
	('Montes de Oca', 'San José'),
	('Turrubares', 'San José'),
	('Dota', 'San José'),
	('Curridabat', 'San José'),
	('Pérez Zeledón', 'San José'),
	('León Cortés', 'San José'),


	/*Cantones de Alajuela*/
	('Alajuela', 'Alajuela'),
	('San Ramón', 'Alajuela'),
	('Grecia', 'Alajuela'),
	('San Mateo', 'Alajuela'),
	('Atenas', 'Alajuela'),
	('Naranjo', 'Alajuela'),
	('Palmares', 'Alajuela'),
	('Poás', 'Alajuela'),
	('Orotina', 'Alajuela'),
	('San Carlos', 'Alajuela'),
	('Zarcero', 'Alajuela'),
	('Sarchí', 'Alajuela'),
	('Upala', 'Alajuela'),
	('Los Chiles', 'Alajuela'),
	('Guatuso', 'Alajuela'),
	('Río Cuarto', 'Alajuela'),


	/*Cantones de Cartago*/
	('Cartago', 'Cartago'),
	('Paraíso', 'Cartago'),
	('La Unión', 'Cartago'),
	('Jiménez', 'Cartago'),
	('Turrialba', 'Cartago'),
	('Alvarado', 'Cartago'),
	('Oreamuno', 'Cartago'),
	('El Guarco', 'Cartago'),


	/*Cantones de Heredia*/
	('Heredia', 'Heredia'),
	('Barva', 'Heredia'),
	('Santo Domingo', 'Heredia'),
	('Santa Bárbara', 'Heredia'),
	('San Rafael', 'Heredia'),
	('San Isidro', 'Heredia'),
	('Belén', 'Heredia'),
	('Flores', 'Heredia'),
	('San Pablo', 'Heredia'),
	('Sarapiquí', 'Heredia'),


	/*Cantones de Guanacaste*/
	('Liberia', 'Guanacaste'),
	('Nicoya', 'Guanacaste'),
	('Santa Cruz', 'Guanacaste'),
	('Bagaces', 'Guanacaste'),
	('Carrillo', 'Guanacaste'),
	('Cañas', 'Guanacaste'),
	('Abangares', 'Guanacaste'),
	('Tilarán', 'Guanacaste'),
	('Nandayure', 'Guanacaste'),
	('La Cruz', 'Guanacaste'),
	('Hojancha', 'Guanacaste'),


	/*Cantones de Puntarenas*/
	('Puntarenas', 'Puntarenas'),
	('Esparza', 'Puntarenas'),
	('Buenos Aires', 'Puntarenas'),
	('Montes de Oro', 'Puntarenas'),
	('Osa', 'Puntarenas'),
	('Quepos', 'Puntarenas'),
	('Golfito', 'Puntarenas'),
	('Coto Brus', 'Puntarenas'),
	('Parrita', 'Puntarenas'),
	('Corredores', 'Puntarenas'),
	('Garabito', 'Puntarenas'),


	/*Cantones de Limón*/
	('Limón', 'Limón'),
	('Pococí', 'Limón'),
	('Siquirres', 'Limón'),
	('Talamanca', 'Limón'),
	('Matina', 'Limón'),
	('Guácimo', 'Limón')


) 
AS Source ([Name], Province_Name)
ON TARGET.Name = Source.Name
WHEN NOT MATCHED BY TARGET THEN
INSERT ([Name], Province_Name)
VALUES ([Name],Province_Name);


MERGE INTO District AS TARGET 
USING (VALUES
	/*Distritos de San José*/
	('Carmen', 'San José', 'San José'), 
	('Merced', 'San José', 'San José'),
	('Hospital', 'San José', 'San José'),
	('Catedral', 'San José', 'San José'),
	('Zapote', 'San José', 'San José'),
	('San Francisco', 'San José', 'San José'),
	('La Uruca', 'San José', 'San José'),
	('Mata Redonda', 'San José', 'San José'),
	('Pavas', 'San José', 'San José'),
	('Hatillo', 'San José', 'San José'),
	('San Sebastián', 'San José', 'San José'),
	('Escazú', 'San José', 'Escazú'),
	('San Antonio', 'San José', 'Escazú'),
	('San Rafael', 'San José', 'Escazú'),
	('Desamparados', 'San José', 'Desamparados'),
	('San Miguel', 'San José', 'Desamparados'),
	('San Juan de D.', 'San José', 'Desamparados'),
	('San Rafael Ar.', 'San José', 'Desamparados'),
	('San Antonio', 'San José', 'Desamparados'),
	('Frailes', 'San José', 'Desamparados'),
	('Patarrá', 'San José', 'Desamparados'),
	('San Cristóbal', 'San José', 'Desamparados'),
	('Rosario', 'San José', 'Desamparados'),
	('Damas', 'San José', 'Desamparados'),
	('San Rafael Ab.', 'San José', 'Desamparados'),
	('Gravilias', 'San José', 'Desamparados'),
	('Los Guido', 'San José', 'Desamparados'),
	('Santiago', 'San José', 'Puriscal'),
	('Mercedes Sur', 'San José', 'Puriscal'),
	('Barbacoas', 'San José', 'Puriscal'),
	('Grifo Alto', 'San José', 'Puriscal'),
	('San Rafael', 'San José', 'Puriscal'),
	('Candelarita', 'San José', 'Puriscal'),
	('Desamparaditos', 'San José', 'Puriscal'),
	('San Antonio', 'San José', 'Puriscal'),
	('Chires', 'San José', 'Puriscal'),
	('San Marcos', 'San José', 'Tarrazú'),
	('San Lorenzo', 'San José', 'Tarrazú'),
	('San Carlos', 'San José', 'Tarrazú'),
	('Aserrí', 'San José', 'Aserrí'),
	('Tarbaca', 'San José', 'Aserrí'),
	('Vuelta de Jorco', 'San José', 'Aserrí'),
	('San Gabriel', 'San José', 'Aserrí'),
	('Legua', 'San José', 'Aserrí'),
	('Monterrey', 'San José', 'Aserrí'),
	('Salitrillos', 'San José', 'Aserrí'),
	('Colón', 'San José', 'Mora'),
	('Guayabo', 'San José', 'Mora'),
	('Tabarcia', 'San José', 'Mora'),
	('Piedras Negras', 'San José', 'Mora'),
	('Picagres', 'San José', 'Mora'),
	('Jaris', 'San José', 'Mora'),
	('Quitirrisí', 'San José', 'Mora'),
	('Guadalupe', 'San José', 'Goicoechea'),
	('San Francisco', 'San José', 'Goicoechea'),
	('Calle Blancos', 'San José', 'Goicoechea'),
	('Mata de Plátano', 'San José', 'Goicoechea'),
	('Ipís', 'San José', 'Goicoechea'),
	('Rancho Redondo', 'San José', 'Goicoechea'),
	('Purral', 'San José', 'Goicoechea'),
	('Santa Ana', 'San José', 'Santa Ana'),
	('Salitral', 'San José', 'Santa Ana'),
	('Pozos', 'San José', 'Santa Ana'),
	('Uruca', 'San José', 'Santa Ana'),
	('Piedades', 'San José', 'Santa Ana'),
	('Brasil', 'San José', 'Santa Ana'),
	('Alajuelita', 'San José', 'Alajuelita'),
	('San Josecito', 'San José', 'Alajuelita'),
	('San Antonio', 'San José', 'Alajuelita'),
	('Concepción', 'San José', 'Alajuelita'),
	('San Felipe', 'San José', 'Alajuelita'),
	('San Isidro', 'San José', 'Coronado'),
	('San Rafael', 'San José', 'Coronado'),
	('Dulce Nombre', 'San José', 'Coronado'),
	('Patalillo', 'San José', 'Coronado'),
	('Cascajal', 'San José', 'Coronado'),
	('San Ignacio', 'San José', 'Acosta'),
	('Guaitil', 'San José', 'Acosta'),
	('Palmichal', 'San José', 'Acosta'),
	('Cangrejal', 'San José', 'Acosta'),
	('Sabanillas', 'San José', 'Acosta'),
	('San Juan', 'San José', 'Tibás'),
	('Cinco Esquinas', 'San José', 'Tibás'),
	('Llorente', 'San José', 'Tibás'),
	('León XIII', 'San José', 'Tibás'),
	('Colima', 'San José', 'Tibás'),
	('San Vicente', 'San José', 'Moravia'),
	('San Jerónimo', 'San José', 'Moravia'),
	('La Trinidad', 'San José', 'Moravia'),
	('San Pedro', 'San José', 'Montes de Oca'),
	('Sabanilla', 'San José', 'Montes de Oca'),
	('Mercedes', 'San José', 'Montes de Oca'),
	('San Rafael', 'San José', 'Montes de Oca'),
	('San Pablo', 'San José', 'Turrubares'),
	('San Pedro', 'San José', 'Turrubares'),
	('San Juan de Ma.', 'San José', 'Turrubares'),
	('San Luis', 'San José', 'Turrubares'),
	('Carara', 'San José', 'Turrubares'),
	('Santa María', 'San José', 'Dota'),
	('Jardín', 'San José', 'Dota'),
	('Copey', 'San José', 'Dota'),
	('Curridabat', 'San José', 'Curridabat'),
	('Granadilla', 'San José', 'Curridabat'),
	('Sánchez', 'San José', 'Curridabat'),
	('Tirrases', 'San José', 'Curridabat'),
	('San Isidro', 'San José', 'Pérez Zeledón'),
	('El General', 'San José', 'Pérez Zeledón'),
	('Daniel Flores', 'San José', 'Pérez Zeledón'),
	('Rivas', 'San José', 'Pérez Zeledón'),
	('San Pedro', 'San José', 'Pérez Zeledón'),
	('Platanares', 'San José', 'Pérez Zeledón'),
	('Pejibaye', 'San José', 'Pérez Zeledón'),
	('Cajón', 'San José', 'Pérez Zeledón'),
	('Barú', 'San José', 'Pérez Zeledón'),
	('Río Nuevo', 'San José', 'Pérez Zeledón'),
	('Páramo', 'San José', 'Pérez Zeledón'),
	('La Amistad', 'San José', 'Pérez Zeledón'),
	('San Pablo', 'San José', 'León Cortés'),
	('San Andrés', 'San José', 'León Cortés'),
	('Llano Bonito', 'San José', 'León Cortés'),
	('San Isidro', 'San José', 'León Cortés'),
	('Santa Cruz', 'San José', 'León Cortés'), 
	('San Antonio', 'San José', 'León Cortés'),
	
	
	/*Distritos de Alajuela*/
	('Alajuela', 'Alajuela', 'Alajuela'),
	('San José', 'Alajuela', 'Alajuela'),
	('Carrizal', 'Alajuela', 'Alajuela'),
	('San Antonio', 'Alajuela', 'Alajuela'),
	('Guácima', 'Alajuela', 'Alajuela'),
	('San Isidro', 'Alajuela', 'Alajuela'),
	('Sabanilla', 'Alajuela', 'Alajuela'),
	('San Rafael', 'Alajuela', 'Alajuela'),
	('Río Segundo', 'Alajuela', 'Alajuela'),
	('Desamparados', 'Alajuela', 'Alajuela'),
	('Turrúcares', 'Alajuela', 'Alajuela'),
	('La Garita', 'Alajuela', 'Alajuela'),
	('Sarapiquí', 'Alajuela', 'Alajuela'),
	('San Ramón', 'Alajuela', 'San Ramón'),
	('Santiago', 'Alajuela', 'San Ramón'),
	('San Juan', 'Alajuela', 'San Ramón'),
	('Piedades Norte', 'Alajuela', 'San Ramón'),
	('Piedades Sur', 'Alajuela', 'San Ramón'),
	('San Rafael', 'Alajuela', 'San Ramón'),
	('San Isidro', 'Alajuela', 'San Ramón'),
	('Ángeles', 'Alajuela', 'San Ramón'),
	('Alfaro', 'Alajuela', 'San Ramón'),
	('Volio', 'Alajuela', 'San Ramón'),
	('Concepción', 'Alajuela', 'San Ramón'),
	('Zapotal', 'Alajuela', 'San Ramón'),
	('Peñas Blancas', 'Alajuela', 'San Ramón'),
	('San Lorenzo', 'Alajuela', 'San Ramón'),
	('Grecia', 'Alajuela', 'Grecia'),
	('San Isidro', 'Alajuela', 'Grecia'),
	('San José', 'Alajuela', 'Grecia'),
	('San Roque', 'Alajuela', 'Grecia'),
	('Tacares', 'Alajuela', 'Grecia'),
	('Puente de Pied.', 'Alajuela', 'Grecia'),
	('Bolívar', 'Alajuela', 'Grecia'),
	('San Mateo', 'Alajuela', 'San Mateo'),
	('Desmonte', 'Alajuela', 'San Mateo'),
	('Jesús María', 'Alajuela', 'San Mateo'),
	('Labrador', 'Alajuela', 'San Mateo'),
	('Atenas', 'Alajuela', 'Atenas'),
	('Jesús', 'Alajuela', 'Atenas'),
	('Mercedes', 'Alajuela', 'Atenas'),
	('San Isidro', 'Alajuela', 'Atenas'),
	('Concepción', 'Alajuela', 'Atenas'),
	('San José', 'Alajuela', 'Atenas'),
	('Santa Eulalia', 'Alajuela', 'Atenas'),
	('Escobal', 'Alajuela', 'Atenas'),
	('Naranjo', 'Alajuela', 'Naranjo'),
	('San Miguel', 'Alajuela', 'Naranjo'),
	('San José', 'Alajuela', 'Naranjo'),
	('Cirrí Sur', 'Alajuela', 'Naranjo'),
	('San Jerónimo', 'Alajuela', 'Naranjo'),
	('San Juan', 'Alajuela', 'Naranjo'),
	('El Rosario', 'Alajuela', 'Naranjo'),
	('Palmitos', 'Alajuela', 'Naranjo'),
	('Palmares', 'Alajuela', 'Palmares'),
	('Zaragoza', 'Alajuela', 'Palmares'),
	('Buenos Aires', 'Alajuela', 'Palmares'),
	('Santiago', 'Alajuela', 'Palmares'),
	('Candelaria', 'Alajuela', 'Palmares'),
	('Esquipulas', 'Alajuela', 'Palmares'),
	('La Granja', 'Alajuela', 'Palmares'),
	('San Pedro', 'Alajuela', 'Poás'),
	('San Juan', 'Alajuela', 'Poás'),
	('San Rafael', 'Alajuela', 'Poás'),
	('Carrillos', 'Alajuela', 'Poás'),
	('Sabana Redonda', 'Alajuela', 'Poás'),
	('Orotina', 'Alajuela', 'Orotina'),
	('El Mastate', 'Alajuela', 'Orotina'),
	('Hacienda Vieja', 'Alajuela', 'Orotina'),
	('Coyolar', 'Alajuela', 'Orotina'),
	('La Ceiba', 'Alajuela', 'Orotina'),
	('Quesada', 'Alajuela', 'San Carlos'),
	('Florencia', 'Alajuela', 'San Carlos'),
	('Buenavista', 'Alajuela', 'San Carlos'),
	('Aguas Zarcas', 'Alajuela', 'San Carlos'),
	('Venecia', 'Alajuela', 'San Carlos'),
	('Pital', 'Alajuela', 'San Carlos'),
	('La Fortuna', 'Alajuela', 'San Carlos'),
	('La Tigra', 'Alajuela', 'San Carlos'),
	('La Palmera', 'Alajuela', 'San Carlos'),
	('Venado', 'Alajuela', 'San Carlos'),
	('Cutris', 'Alajuela', 'San Carlos'),
	('Monterrey', 'Alajuela', 'San Carlos'),
	('Pocosol', 'Alajuela', 'San Carlos'),
	('Zarcero', 'Alajuela', 'Zarcero'),
	('Laguna', 'Alajuela', 'Zarcero'),
	('Tapesco', 'Alajuela', 'Zarcero'),
	('Guadalupe', 'Alajuela', 'Zarcero'),
	('Palmira', 'Alajuela', 'Zarcero'),
	('Zapote', 'Alajuela', 'Zarcero'),
	('Brisas', 'Alajuela', 'Zarcero'),
	('Sarchí Norte', 'Alajuela', 'Sarchí'),
	('Sarchí Sur', 'Alajuela', 'Sarchí'),
	('Toro Amarillo', 'Alajuela', 'Sarchí'),
	('San Pedro', 'Alajuela', 'Sarchí'),
	('Rodríguez', 'Alajuela', 'Sarchí'),
	('Upala', 'Alajuela', 'Upala'),
	('Aguas Claras', 'Alajuela', 'Upala'),
	('San José Pizote', 'Alajuela', 'Upala'),
	('Bijagua', 'Alajuela', 'Upala'),
	('Delicias', 'Alajuela', 'Upala'),
	('Dos Ríos', 'Alajuela', 'Upala'),
	('Yolillal', 'Alajuela', 'Upala'),
	('Canalete', 'Alajuela', 'Upala'),
	('Los Chiles', 'Alajuela', 'Los Chiles'),
	('Caño Negro', 'Alajuela', 'Los Chiles'),
	('El Amparo', 'Alajuela', 'Los Chiles'),
	('San Jorge', 'Alajuela', 'Los Chiles'),
	('San Rafael', 'Alajuela', 'Guatuso'),
	('Buenavista', 'Alajuela', 'Guatuso'),
	('Cote', 'Alajuela', 'Guatuso'),
	('Katira', 'Alajuela', 'Guatuso'),
	('Río Cuarto', 'Alajuela', 'Río Cuarto'),
	('Santa Rita', 'Alajuela', 'Río Cuarto'),
	('Santa Isabel', 'Alajuela', 'Río Cuarto'), 
	

	/*Distritos de Cartago*/
	('Oriental', 'Cartago', 'Cartago'),
	('Occidental', 'Cartago', 'Cartago'),
	('Carmen', 'Cartago', 'Cartago'),
	('San Nicolás', 'Cartago', 'Cartago'),
	('Agua Caliente', 'Cartago', 'Cartago'),
	('Guadalupe', 'Cartago', 'Cartago'),
	('Corralillo', 'Cartago', 'Cartago'),
	('Tierra Blanca', 'Cartago', 'Cartago'),
	('Dulce Nombre', 'Cartago', 'Cartago'),
	('Llano Grande', 'Cartago', 'Cartago'),
	('Quebradilla', 'Cartago', 'Cartago'),
	('Paraíso', 'Cartago', 'Paraíso'),
	('Santiago', 'Cartago', 'Paraíso'),
	('Orosi', 'Cartago', 'Paraíso'),
	('Cachí', 'Cartago', 'Paraíso'),
	('Santa Lucía', 'Cartago', 'Paraíso'),
	('Tres Ríos', 'Cartago', 'La Unión'),
	('San Diego', 'Cartago', 'La Unión'),
	('San Juan', 'Cartago', 'La Unión'),
	('San Rafael', 'Cartago', 'La Unión'),
	('Concepción', 'Cartago', 'La Unión'),
	('Dulce Nombre', 'Cartago', 'La Unión'),
	('San Ramón', 'Cartago', 'La Unión'),
	('Río Azul', 'Cartago', 'La Unión'),
	('Juan Viñas', 'Cartago', 'Jiménez'),
	('Tucurrique', 'Cartago', 'Jiménez'),
	('Pejibaye', 'Cartago', 'Jiménez'),
	('Turrialba', 'Cartago', 'Turrialba'),
	('La Suiza', 'Cartago', 'Turrialba'),
	('Peralta', 'Cartago', 'Turrialba'),
	('Santa Cruz', 'Cartago', 'Turrialba'),
	('Santa Teresita', 'Cartago', 'Turrialba'),
	('Pavones', 'Cartago', 'Turrialba'),
	('Tuis', 'Cartago', 'Turrialba'),
	('Tayutic', 'Cartago', 'Turrialba'),
	('Santa Rosa', 'Cartago', 'Turrialba'),
	('Tres Equis', 'Cartago', 'Turrialba'),
	('La Isabel', 'Cartago', 'Turrialba'),
	('Chirripó', 'Cartago', 'Turrialba'),
	('Pacayas', 'Cartago', 'Alvarado'),
	('Cervantes', 'Cartago', 'Alvarado'),
	('Capellades', 'Cartago', 'Alvarado'),
	('San Rafael', 'Cartago', 'Oreamuno'),
	('Cot', 'Cartago', 'Oreamuno'),
	('Potrero Cerrado', 'Cartago', 'Oreamuno'),
	('Cipreses', 'Cartago', 'Oreamuno'),
	('Santa Rosa', 'Cartago', 'Oreamuno'),
	('El Tejar', 'Cartago', 'El Guarco'),
	('San Isidro', 'Cartago', 'El Guarco'),
	('Tobosi', 'Cartago', 'El Guarco'),
	('Patio de Agua', 'Cartago', 'El Guarco'),


	/*Distritos de Heredia*/
	('Heredia', 'Heredia', 'Heredia'),
	('Mercedes', 'Heredia', 'Heredia'),
	('San Francisco', 'Heredia', 'Heredia'),
	('Ulloa', 'Heredia', 'Heredia'),
	('Varablanca', 'Heredia', 'Heredia'),
	('Barva', 'Heredia', 'Barva'),
	('San Pedro', 'Heredia', 'Barva'),
	('San Pablo', 'Heredia', 'Barva'),
	('San Roque', 'Heredia', 'Barva'),
	('Santa Lucía', 'Heredia', 'Barva'),
	('San José Monta.', 'Heredia', 'Barva'),
	('Santo Domingo', 'Heredia', 'Santo Domingo'),
	('San Vicente', 'Heredia', 'Santo Domingo'),
	('San Miguel', 'Heredia', 'Santo Domingo'),
	('Paracito', 'Heredia', 'Santo Domingo'),
	('Santo Tomás', 'Heredia', 'Santo Domingo'),
	('Santa Rosa', 'Heredia', 'Santo Domingo'),
	('Tures', 'Heredia', 'Santo Domingo'),
	('Pará', 'Heredia', 'Santo Domingo'),
	('Santa Bárbara', 'Heredia', 'Santa Bárbara'),
	('San Pedro', 'Heredia', 'Santa Bárbara'),
	('San Juan', 'Heredia', 'Santa Bárbara'),
	('Jesús', 'Heredia', 'Santa Bárbara'),
	('Santo Domingo', 'Heredia', 'Santa Bárbara'),
	('Purabá', 'Heredia', 'Santa Bárbara'),
	('San Rafael', 'Heredia', 'San Rafael'),
	('San Josecito', 'Heredia', 'San Rafael'),
	('Santiago', 'Heredia', 'San Rafael'),
	('Ángeles', 'Heredia', 'San Rafael'),
	('Concepción', 'Heredia', 'San Rafael'),
	('San Isidro', 'Heredia', 'San Isidro'),
	('San José', 'Heredia', 'San Isidro'),
	('Concepción', 'Heredia', 'San Isidro'),
	('San Francisco', 'Heredia', 'San Isidro'),
	('San Antonio', 'Heredia', 'Belén'),
	('La Ribera', 'Heredia', 'Belén'),
	('La Asunción', 'Heredia', 'Belén'),
	('San Joaquín', 'Heredia', 'Flores'),
	('Barrantes', 'Heredia', 'Flores'),
	('Llorente', 'Heredia', 'Flores'),
	('San Pablo', 'Heredia', 'San Pablo'),
	('Rincón de Saba.', 'Heredia', 'San Pablo'),
	('Puerto Viejo', 'Heredia', 'Sarapiquí'),
	('La Virgen', 'Heredia', 'Sarapiquí'),
	('Horquetas', 'Heredia', 'Sarapiquí'),
	('Llanuras Gaspar', 'Heredia', 'Sarapiquí'),
	('Cureña', 'Heredia', 'Sarapiquí'),


	/*Distritos de Guanacaste*/
	('Liberia', 'Guanacaste', 'Liberia'),
	('Cañas Dulces', 'Guanacaste', 'Liberia'),
	('Mayorga', 'Guanacaste', 'Liberia'),
	('Nacascolo', 'Guanacaste', 'Liberia'),
	('Curubandé', 'Guanacaste', 'Liberia'),
	('Nicoya', 'Guanacaste', 'Nicoya'),
	('Mansión', 'Guanacaste', 'Nicoya'),
	('San Antonio', 'Guanacaste', 'Nicoya'),
	('Quebrada Honda', 'Guanacaste', 'Nicoya'),
	('Sámara', 'Guanacaste', 'Nicoya'),
	('Nosara', 'Guanacaste', 'Nicoya'),
	('Belén de Nosar.', 'Guanacaste', 'Nicoya'),
	('Santa Cruz', 'Guanacaste', 'Santa Cruz'),
	('Bolsón', 'Guanacaste', 'Santa Cruz'),
	('Veintisiete Ab.', 'Guanacaste', 'Santa Cruz'),
	('Tempate', 'Guanacaste', 'Santa Cruz'),
	('Cartagena', 'Guanacaste', 'Santa Cruz'),
	('Cuajiniquil', 'Guanacaste', 'Santa Cruz'),
	('Diriá', 'Guanacaste', 'Santa Cruz'),
	('Cabo Velas', 'Guanacaste', 'Santa Cruz'),
	('Tamarindo', 'Guanacaste', 'Santa Cruz'),
	('Bagaces', 'Guanacaste', 'Bagaces'),
	('La Fortuna', 'Guanacaste', 'Bagaces'),
	('Mogote', 'Guanacaste', 'Bagaces'),
	('Río Naranjo', 'Guanacaste', 'Bagaces'),
	('Filadelfia', 'Guanacaste', 'Carrillo'),
	('Palmira', 'Guanacaste', 'Carrillo'),
	('Sardinal', 'Guanacaste', 'Carrillo'),
	('Belén', 'Guanacaste', 'Carrillo'),
	('Cañas', 'Guanacaste', 'Cañas'),
	('Palmira', 'Guanacaste', 'Cañas'),
	('San Miguel', 'Guanacaste', 'Cañas'),
	('Bebedero', 'Guanacaste', 'Cañas'),
	('Porozal', 'Guanacaste', 'Cañas'),
	('Las Juntas', 'Guanacaste', 'Abangares'),
	('Sierra', 'Guanacaste', 'Abangares'),
	('San Juan', 'Guanacaste', 'Abangares'),
	('Colorado', 'Guanacaste', 'Abangares'),
	('Tilarán', 'Guanacaste', 'Tilarán'),
	('Quebrada Grande', 'Guanacaste', 'Tilarán'),
	('Tronadora', 'Guanacaste', 'Tilarán'),
	('Santa Rosa', 'Guanacaste', 'Tilarán'),
	('Líbano', 'Guanacaste', 'Tilarán'),
	('Tierras Morenas', 'Guanacaste', 'Tilarán'),
	('Arenal', 'Guanacaste', 'Tilarán'),
	('Cabeceras', 'Guanacaste', 'Tilarán'),
	('Carmona', 'Guanacaste', 'Nandayure'),
	('Santa Rita', 'Guanacaste', 'Nandayure'),
	('Zapotal', 'Guanacaste', 'Nandayure'),
	('San Pablo', 'Guanacaste', 'Nandayure'),
	('Porvenir', 'Guanacaste', 'Nandayure'),
	('Bejuco', 'Guanacaste', 'Nandayure'),
	('La Cruz', 'Guanacaste', 'La Cruz'),
	('Santa Cecilia', 'Guanacaste', 'La Cruz'),
	('La Garita', 'Guanacaste', 'La Cruz'),
	('Santa Elena', 'Guanacaste', 'La Cruz'),
	('Hojancha', 'Guanacaste', 'Hojancha'),
	('Monte Romo', 'Guanacaste', 'Hojancha'),
	('Puerto Carrillo', 'Guanacaste', 'Hojancha'),
	('Huacas', 'Guanacaste', 'Hojancha'),
	('Matambú', 'Guanacaste', 'Hojancha'), 


	/*Distritos de Puntarenas*/
	('Puntarenas', 'Puntarenas', 'Puntarenas'),
	('Pitahaya', 'Puntarenas', 'Puntarenas'),
	('Chomes', 'Puntarenas', 'Puntarenas'),
	('Lepanto', 'Puntarenas', 'Puntarenas'),
	('Paquera', 'Puntarenas', 'Puntarenas'),
	('Manzanillo', 'Puntarenas', 'Puntarenas'),
	('Guacimal', 'Puntarenas', 'Puntarenas'),
	('Barranca', 'Puntarenas', 'Puntarenas'),
	('Monte Verde', 'Puntarenas', 'Puntarenas'),
	('Isla del Coco', 'Puntarenas', 'Puntarenas'),
	('Cóbano', 'Puntarenas', 'Puntarenas'),
	('Chacarita', 'Puntarenas', 'Puntarenas'),
	('Chira', 'Puntarenas', 'Puntarenas'),
	('Acapulco', 'Puntarenas', 'Puntarenas'),
	('El Roble', 'Puntarenas', 'Puntarenas'),
	('Arancibia', 'Puntarenas', 'Puntarenas'),
	('Espíritu Santo', 'Puntarenas', 'Esparza'),
	('San Juan Grande', 'Puntarenas', 'Esparza'),
	('Macacona', 'Puntarenas', 'Esparza'),
	('San Rafael', 'Puntarenas', 'Esparza'),
	('San Jerónimo', 'Puntarenas', 'Esparza'),
	('Caldera', 'Puntarenas', 'Esparza'),
	('Buenos Aires', 'Puntarenas', 'Buenos Aires'),
	('Volcán', 'Puntarenas', 'Buenos Aires'),
	('Potrero Grande', 'Puntarenas', 'Buenos Aires'),
	('Boruca', 'Puntarenas', 'Buenos Aires'),
	('Pilas', 'Puntarenas', 'Buenos Aires'),
	('Colinas', 'Puntarenas', 'Buenos Aires'),
	('Chánguena', 'Puntarenas', 'Buenos Aires'),
	('Biolley', 'Puntarenas', 'Buenos Aires'),
	('Brunka', 'Puntarenas', 'Buenos Aires'),
	('Miramar', 'Puntarenas', 'Montes de Oro'),
	('La Unión', 'Puntarenas', 'Montes de Oro'),
	('San Isidro', 'Puntarenas', 'Montes de Oro'),
	('Puerto Cortés', 'Puntarenas', 'Osa'),
	('Palmar', 'Puntarenas', 'Osa'),
	('Sierpe', 'Puntarenas', 'Osa'),
	('Bahía Ballena', 'Puntarenas', 'Osa'),
	('Piedras Blancas', 'Puntarenas', 'Osa'),
	('Bahía Drake', 'Puntarenas', 'Osa'),
	('Quepos', 'Puntarenas', 'Quepos'),
	('Savegre', 'Puntarenas', 'Quepos'),
	('Naranjito', 'Puntarenas', 'Quepos'),
	('Golfito', 'Puntarenas', 'Golfito'),
	('Puerto Jiménez', 'Puntarenas', 'Golfito'),
	('Guaycará', 'Puntarenas', 'Golfito'),
	('Pavón', 'Puntarenas', 'Golfito'),
	('San Vito', 'Puntarenas', 'Coto Brus'),
	('Sabalito', 'Puntarenas', 'Coto Brus'),
	('Aguabuena', 'Puntarenas', 'Coto Brus'),
	('Limoncito', 'Puntarenas', 'Coto Brus'),
	('Pittier', 'Puntarenas', 'Coto Brus'),
	('Gutiérrez Braun', 'Puntarenas', 'Coto Brus'),
	('Parrita', 'Puntarenas', 'Parrita'),
	('Corredor', 'Puntarenas', 'Corredores'),
	('La Cuesta', 'Puntarenas', 'Corredores'),
	('Canoas', 'Puntarenas', 'Corredores'),
	('Laurel', 'Puntarenas', 'Corredores'),
	('Jacó', 'Puntarenas', 'Garabito'),
	('Tárcoles', 'Puntarenas', 'Garabito'), 


	/*Distritos de Limón*/
	('Limón', 'Limón', 'Limón'),
	('Valle La Estre.', 'Limón', 'Limón'),
	('Río Blanco', 'Limón', 'Limón'),
	('Matama', 'Limón', 'Limón'),
	('Guápiles', 'Limón', 'Pococí'),
	('Jiménez', 'Limón', 'Pococí'),
	('La Rita', 'Limón', 'Pococí'),
	('Roxana', 'Limón', 'Pococí'),
	('Cariari', 'Limón', 'Pococí'),
	('Colorado', 'Limón', 'Pococí'),
	('La Colonia', 'Limón', 'Pococí'),
	('Siquirres', 'Limón', 'Siquirres'),
	('Pacuarito', 'Limón', 'Siquirres'),
	('Florida', 'Limón', 'Siquirres'),
	('Germania', 'Limón', 'Siquirres'),
	('El Cairo', 'Limón', 'Siquirres'),
	('Alegría', 'Limón', 'Siquirres'),
	('Reventazón', 'Limón', 'Siquirres'),
	('Bratsi', 'Limón', 'Talamanca'),
	('Sixaola', 'Limón', 'Talamanca'),
	('Cahuita', 'Limón', 'Talamanca'),
	('Telire', 'Limón', 'Talamanca'),
	('Matina', 'Limón', 'Matina'),
	('Batán', 'Limón', 'Matina'),
	('Carrandi', 'Limón', 'Matina'),
	('Guácimo', 'Limón', 'Guácimo'),
	('Mercedes', 'Limón', 'Guácimo'),
	('Pocora', 'Limón', 'Guácimo'),
	('Río Jiménez', 'Limón', 'Guácimo'),
	('Duacarí', 'Limón', 'Guácimo')



)
AS Source ([Name], Province_Name, Canton_Name)
ON TARGET.Name = Source.Name
WHEN NOT MATCHED BY TARGET THEN
INSERT ([Name], Province_Name, Canton_Name)
VALUES ([Name],Province_Name, Canton_Name);